//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class agenda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public agenda()
        {
            this.cedulas = new HashSet<cedula>();
            this.detallecedulas = new HashSet<detallecedula>();
            this.detalleprogramas = new HashSet<detalleprograma>();
            this.indices = new HashSet<index>();
            this.programas = new HashSet<programa>();
            this.agendas1 = new HashSet<agenda>();
        }
    
        public int idagenda { get; set; }
        public Nullable<int> idcedula { get; set; }
        public string fechacreadoagenda { get; set; }
        public string fechaterminacionagenda { get; set; }
        public string fecharevisionagenda { get; set; }
        public string fechaaprobacionagenda { get; set; }
        public string encabezadoagenda { get; set; }
        public string descripcionagenda { get; set; }
        public string estadoprocesoagenda { get; set; }
        public string comentariorespuestaagenda { get; set; }
        public string estadoagenda { get; set; }
        public Nullable<int> isuso { get; set; }
        public Nullable<int> idencargo { get; set; }
        public Nullable<int> idusuarioasigna { get; set; }
        public Nullable<int> idusuarioresponable { get; set; }
        public Nullable<int> padreidagenda { get; set; }
        public Nullable<int> idgenerico { get; set; }
        public string tabla { get; set; }
        public string referenciapapel { get; set; }
        public string usuariocerro { get; set; }
        public string usuarioaprobo { get; set; }
        public string usuariosuperviso { get; set; }
        public string fechasupervision { get; set; }
        public string fechaaprobacion { get; set; }
        public string fechacierre { get; set; }
        public string etapapapel { get; set; }
        public string uuid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cedula> cedulas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detallecedula> detallecedulas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalleprograma> detalleprogramas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<index> indices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<programa> programas { get; set; }
        public virtual cedula cedula { get; set; }
        public virtual encargo encargo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<agenda> agendas1 { get; set; }
        public virtual agenda agenda1 { get; set; }
        public virtual usuario usuario { get; set; }
        public virtual usuario usuario1 { get; set; }
    }
}
