//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class asignacione
    {
        public int idasignacion { get; set; }
        public Nullable<int> idusuario { get; set; }
        public int idencargo { get; set; }
        public string fechacreaasignacion { get; set; }
        public Nullable<decimal> horasplanasignacion { get; set; }
        public Nullable<decimal> horasejecucionasignacion { get; set; }
        public Nullable<decimal> preciohoraasignacion { get; set; }
        public string estadoasignacion { get; set; }
        public Nullable<int> isuso { get; set; }
        public string uuid { get; set; }
    
        public virtual usuario usuario { get; set; }
        public virtual encargo encargo { get; set; }
    }
}
