//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class balance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public balance()
        {
            this.cedulas = new HashSet<cedula>();
            this.materialidads = new HashSet<materialidad>();
            this.matrizriesgos = new HashSet<matrizriesgo>();
            this.detallebalances = new HashSet<detallebalance>();
            this.cedulas1 = new HashSet<cedula>();
            this.partidas = new HashSet<partida>();
        }
    
        public int idbalance { get; set; }
        public int idcb { get; set; }
        public int idperiodos { get; set; }
        public string fechasistemabalance { get; set; }
        public string fechabalancebalance { get; set; }
        public string estadobalance { get; set; }
        public int idscbalance { get; set; }
        public Nullable<int> isuso { get; set; }
        public string uuid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cedula> cedulas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<materialidad> materialidads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<matrizriesgo> matrizriesgos { get; set; }
        public virtual clasesbalance clasesbalance { get; set; }
        public virtual sistemascontable sistemascontable { get; set; }
        public virtual periodo periodo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detallebalance> detallebalances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cedula> cedulas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<partida> partidas { get; set; }
    }
}
