//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class bitacora
    {
        public int idbitacora { get; set; }
        public string fechahorabitacora { get; set; }
        public string accionbitacora { get; set; }
        public string nombretablabitacora { get; set; }
        public string detallebitacora { get; set; }
        public Nullable<int> idgenericobitacora { get; set; }
        public Nullable<int> idusuariobitacora { get; set; }
        public Nullable<int> idtransaccionbitacora { get; set; }
        public string uuid { get; set; }
        public Nullable<int> idencargo { get; set; }
    
        public virtual encargo encargo { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
