//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class cedula
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cedula()
        {
            this.agendas = new HashSet<agenda>();
            this.cedulacontactos = new HashSet<cedulacontacto>();
            this.cedulacorrespondencias = new HashSet<cedulacorrespondencia>();
            this.cedularequerimientos = new HashSet<cedularequerimiento>();
            this.cedulareuniones = new HashSet<cedulareunione>();
            this.detallecedulas = new HashSet<detallecedula>();
            this.cedulas1 = new HashSet<cedula>();
            this.marcasauditorias = new HashSet<marcasauditoria>();
            this.notaspts = new HashSet<notaspt>();
            this.cedulaslegales = new HashSet<cedulaslegale>();
            this.confirmaciones = new HashSet<confirmacione>();
            this.detalleprogramas = new HashSet<detalleprograma>();
            this.detallecuestionarios = new HashSet<detallecuestionario>();
            this.hallazgos = new HashSet<hallazgo>();
            this.partidas = new HashSet<partida>();
        }
    
        public int idcedula { get; set; }
        public Nullable<int> idvisita { get; set; }
        public Nullable<int> idindice { get; set; }
        public Nullable<int> idtc { get; set; }
        public Nullable<int> idrepositorio { get; set; }
        public Nullable<int> idencargo { get; set; }
        public string titulocedula { get; set; }
        public string etapapapel { get; set; }
        public string fechacreadocedula { get; set; }
        public string conclusioncedula { get; set; }
        public string objetivocedula { get; set; }
        public string alcancecedula { get; set; }
        public string estadocedula { get; set; }
        public Nullable<int> isuso { get; set; }
        public string referenciacedula { get; set; }
        public Nullable<int> idgenerico { get; set; }
        public string tabla { get; set; }
        public string usuariocerro { get; set; }
        public string usuarioaprobo { get; set; }
        public string usuariosuperviso { get; set; }
        public string fechasupervision { get; set; }
        public string fechaaprobacion { get; set; }
        public string fechacierre { get; set; }
        public Nullable<int> idbalance { get; set; }
        public Nullable<int> idbalanceanterior { get; set; }
        public string uuid { get; set; }
        public Nullable<int> padreidcedula { get; set; }
        public Nullable<int> idpapeles { get; set; }
        public Nullable<int> idagenda { get; set; }
        public Nullable<int> idnotaspt { get; set; }
        public Nullable<decimal> ordencedula { get; set; }
    
        public virtual agenda agenda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<agenda> agendas { get; set; }
        public virtual balance balance { get; set; }
        public virtual balance balance1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cedulacontacto> cedulacontactos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cedulacorrespondencia> cedulacorrespondencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cedularequerimiento> cedularequerimientos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cedulareunione> cedulareuniones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detallecedula> detallecedulas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cedula> cedulas1 { get; set; }
        public virtual cedula cedula1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<marcasauditoria> marcasauditorias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notaspt> notaspts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cedulaslegale> cedulaslegales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<confirmacione> confirmaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalleprograma> detalleprogramas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detallecuestionario> detallecuestionarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hallazgo> hallazgos { get; set; }
        public virtual index index { get; set; }
        public virtual tiposcedula tiposcedula { get; set; }
        public virtual visita visita { get; set; }
        public virtual encargo encargo { get; set; }
        public virtual notaspt notaspt { get; set; }
        public virtual papele papele { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<partida> partidas { get; set; }
        public virtual repositorio repositorio { get; set; }
    }
}
