//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class cedulareunione
    {
        public int idcr { get; set; }
        public Nullable<int> idcedula { get; set; }
        public string fechacr { get; set; }
        public Nullable<decimal> tiempoduracioncr { get; set; }
        public string participanteexternocr { get; set; }
        public string participantesinternocr { get; set; }
        public string asuntocr { get; set; }
        public string conclusionescr { get; set; }
        public string comentariocr { get; set; }
        public string estadocr { get; set; }
        public string referenciapapel { get; set; }
        public Nullable<int> idgenerico { get; set; }
        public string tabla { get; set; }
        public string usuariocerro { get; set; }
        public string usuarioaprobo { get; set; }
        public string usuariosuperviso { get; set; }
        public string fechasupervision { get; set; }
        public string fechaaprobacion { get; set; }
        public string fechacierre { get; set; }
        public string etapapapel { get; set; }
        public Nullable<int> idencargo { get; set; }
        public string uuid { get; set; }
    
        public virtual cedula cedula { get; set; }
        public virtual encargo encargo { get; set; }
    }
}
