//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class cedularequerimiento
    {
        public int idcrequerimiento { get; set; }
        public Nullable<int> idcedula { get; set; }
        public Nullable<int> idindice { get; set; }
        public Nullable<decimal> ordencrequerimiento { get; set; }
        public string descripcioncrequerimiento { get; set; }
        public string formatocrequerimiento { get; set; }
        public string estadocrequerimiento { get; set; }
        public bool sistemacrequerimiento { get; set; }
        public string fechaentregacrequerimiento { get; set; }
        public string estadosolicitudcrequerimient { get; set; }
        public Nullable<int> isuso { get; set; }
        public string referenciapapel { get; set; }
        public Nullable<int> idgenerico { get; set; }
        public string tabla { get; set; }
        public string usuariocerro { get; set; }
        public string usuarioaprobo { get; set; }
        public string usuariosuperviso { get; set; }
        public string fechasupervision { get; set; }
        public string fechaaprobacion { get; set; }
        public string fechacierre { get; set; }
        public string etapapapel { get; set; }
        public Nullable<int> idencargo { get; set; }
        public string uuid { get; set; }
        public Nullable<int> idpapel { get; set; }
    
        public virtual index index { get; set; }
        public virtual cedula cedula { get; set; }
        public virtual encargo encargo { get; set; }
        public virtual papele papele { get; set; }
    }
}
