//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class clasecuenta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public clasecuenta()
        {
            this.catalogocuentas = new HashSet<catalogocuenta>();
            this.clasecuentas1 = new HashSet<clasecuenta>();
        }
    
        public int idccuentas { get; set; }
        public string descripcionccuentas { get; set; }
        public bool sistemaccuentas { get; set; }
        public string estadoccuentas { get; set; }
        public Nullable<int> padreidccuentas { get; set; }
        public string uuid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalogocuenta> catalogocuentas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<clasecuenta> clasecuentas1 { get; set; }
        public virtual clasecuenta clasecuenta1 { get; set; }
    }
}
