//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class conexione
    {
        public int idconexion { get; set; }
        public int idfirma { get; set; }
        public string ipconexion { get; set; }
        public string tipoip { get; set; }
        public bool protocoloconexion { get; set; }
        public int puertoconexion { get; set; }
        public bool principalconexion { get; set; }
        public string estadoconexion { get; set; }
        public string uuid { get; set; }
        public Nullable<int> tipoinstalacionconexion { get; set; }
    }
}
