//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class confirmacione
    {
        public int idconfirmacion { get; set; }
        public Nullable<int> idrepositorio { get; set; }
        public Nullable<int> idcedula { get; set; }
        public Nullable<int> iddb { get; set; }
        public Nullable<decimal> saldocuentaconfirmacion { get; set; }
        public string resultadoobtenidoconfirmacion { get; set; }
        public string estadoconfirmacion { get; set; }
        public Nullable<int> isuso { get; set; }
        public string referenciapapel { get; set; }
        public Nullable<int> idgenerico { get; set; }
        public string tabla { get; set; }
        public string usuariocerro { get; set; }
        public string usuarioaprobo { get; set; }
        public string usuariosuperviso { get; set; }
        public string fechasupervision { get; set; }
        public string fechaaprobacion { get; set; }
        public string fechacierre { get; set; }
        public string etapapapel { get; set; }
        public Nullable<int> idencargo { get; set; }
        public string uuid { get; set; }
    
        public virtual cedula cedula { get; set; }
        public virtual detallebalance detallebalance { get; set; }
        public virtual encargo encargo { get; set; }
        public virtual repositorio repositorio { get; set; }
    }
}
