//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class correspondencia
    {
        public int idcorrespondencia { get; set; }
        public Nullable<int> idpapeles { get; set; }
        public int idusuario { get; set; }
        public int idct { get; set; }
        public string idnitcliente { get; set; }
        public Nullable<int> usuidusuario { get; set; }
        public string numerocorrespondencia { get; set; }
        public string asuntocorrespondencia { get; set; }
        public string firmacorrespondencia { get; set; }
        public string fecharecepcioncorrespondencia { get; set; }
        public string comentariocorrespondencia { get; set; }
        public string aprobacioncorrespondencia { get; set; }
        public string fechacreadocorrespondencia { get; set; }
        public string fechaaprobacioncorrespondenci { get; set; }
        public bool salientecorrespondencia { get; set; }
        public string estadocorrespondencia { get; set; }
        public byte[] archivocorrespondencia { get; set; }
        public string nombrefilecorrespondencia { get; set; }
        public Nullable<int> idcontactofirmacorrespondencia { get; set; }
        public Nullable<int> isuso { get; set; }
        public string uuid { get; set; }
    
        public virtual contacto contacto { get; set; }
        public virtual correspondenciatipos correspondenciatipos { get; set; }
        public virtual usuario usuario { get; set; }
        public virtual usuario usuario1 { get; set; }
    }
}
