//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class costohistoricohora
    {
        public int idchh { get; set; }
        public Nullable<int> idasignacion { get; set; }
        public decimal costochh { get; set; }
        public string fechacreadochh { get; set; }
        public string estadochh { get; set; }
        public string uuid { get; set; }
    }
}
