//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class cronograma
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cronograma()
        {
            this.detallecronogramas = new HashSet<detallecronograma>();
        }
    
        public int idcronograma { get; set; }
        public Nullable<int> idpapeles { get; set; }
        public Nullable<int> idencargo { get; set; }
        public string fechaprogramadacronograma { get; set; }
        public string fechafinalcronograma { get; set; }
        public Nullable<decimal> horastotalesplaneadascronogr { get; set; }
        public string fechacreadocronograma { get; set; }
        public string estadocronograma { get; set; }
        public string uuid { get; set; }
    
        public virtual encargo encargo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detallecronograma> detallecronogramas { get; set; }
        public virtual encargo encargo1 { get; set; }
    }
}
