//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class designacione
    {
        public int iddesignacion { get; set; }
        public Nullable<int> idchh { get; set; }
        public Nullable<int> idusuario { get; set; }
        public Nullable<int> iddc { get; set; }
        public string fechacreadadesignacion { get; set; }
        public Nullable<decimal> horasplandesignacion { get; set; }
        public Nullable<decimal> horasejecuciondesignacion { get; set; }
        public string estadodesignacion { get; set; }
        public Nullable<int> isuso { get; set; }
        public string uuid { get; set; }
    
        public virtual usuario usuario { get; set; }
        public virtual detallecronograma detallecronograma { get; set; }
    }
}
