//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class detallematrizriesgo
    {
        public int iddmr { get; set; }
        public Nullable<int> idprograma { get; set; }
        public Nullable<int> idmaterialidad { get; set; }
        public int idmr { get; set; }
        public string codigocontabledmr { get; set; }
        public string nombredmr { get; set; }
        public decimal saldoevaluaciondmr { get; set; }
        public string factoresriesgodmr { get; set; }
        public string evaluacioninherentedmr { get; set; }
        public string evaluacioncontroldmr { get; set; }
        public string evaluacioncombinadodmr { get; set; }
        public string justificaevaluadmr { get; set; }
        public string clasespruebasdmr { get; set; }
        public string procedimientosdmr { get; set; }
        public Nullable<decimal> alcanceinherentedmr { get; set; }
        public Nullable<decimal> alcancecontroldmr { get; set; }
        public Nullable<decimal> alcancecombinadodmr { get; set; }
        public string justificaalcancedmr { get; set; }
        public Nullable<decimal> materialidaddmr { get; set; }
        public string estadodmr { get; set; }
        public Nullable<int> isuso { get; set; }
        public Nullable<decimal> ordencc { get; set; }
        public Nullable<int> iddp { get; set; }
        public Nullable<int> iddc { get; set; }
        public string uuid { get; set; }
    
        public virtual detallecuestionario detallecuestionario { get; set; }
        public virtual detalleprograma detalleprograma { get; set; }
        public virtual materialidad materialidad { get; set; }
        public virtual matrizriesgo matrizriesgo { get; set; }
        public virtual programa programa { get; set; }
    }
}
