//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class detallecronograma
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public detallecronograma()
        {
            this.designaciones = new HashSet<designacione>();
        }
    
        public int iddc { get; set; }
        public Nullable<int> idpa { get; set; }
        public Nullable<int> idvisita { get; set; }
        public Nullable<int> idcronograma { get; set; }
        public string actividaddc { get; set; }
        public string fechaprogramadacronograma { get; set; }
        public string fechafinaldc { get; set; }
        public Nullable<decimal> horasplaneadasdc { get; set; }
        public string fechacreadodc { get; set; }
        public string estadodc { get; set; }
        public Nullable<int> idusuario { get; set; }
        public Nullable<int> isuso { get; set; }
        public string uuid { get; set; }
    
        public virtual cronograma cronograma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<designacione> designaciones { get; set; }
        public virtual procesosauditoria procesosauditoria { get; set; }
        public virtual visita visita { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
