//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalleherramienta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public detalleherramienta()
        {
            this.detalleherramientas1 = new HashSet<detalleherramienta>();
        }
    
        public int iddh { get; set; }
        public Nullable<int> idusuariodh { get; set; }
        public Nullable<int> idtprocedimiento { get; set; }
        public int idherramienta { get; set; }
        public string descripciondh { get; set; }
        public byte[] descripcionbyteadh { get; set; }
        public string fechacreadodh { get; set; }
        public bool sistemadh { get; set; }
        public string estadodh { get; set; }
        public Nullable<decimal> ordendh { get; set; }
        public Nullable<decimal> horasplandh { get; set; }
        public Nullable<int> idvisitadh { get; set; }
        public Nullable<int> iddhprincipaldh { get; set; }
        public Nullable<int> isuso { get; set; }
        public string uuid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalleherramienta> detalleherramientas1 { get; set; }
        public virtual detalleherramienta detalleherramienta1 { get; set; }
        public virtual tipoprocedimiento tipoprocedimiento { get; set; }
        public virtual usuario usuario { get; set; }
        public virtual visita visita { get; set; }
    }
}
