//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class detallesmaf
    {
        public int iddetallemaf { get; set; }
        public Nullable<int> idmaf { get; set; }
        public Nullable<int> idratio { get; set; }
        public string analisisdetallemaf { get; set; }
        public decimal indicedetallemaf { get; set; }
        public string riesgodetallemaf { get; set; }
        public string cadenadetallemaf { get; set; }
        public Nullable<decimal> indcomparadetallemaf { get; set; }
        public string cadenacomparatdetallemaf { get; set; }
        public string estadodetallemaf { get; set; }
        public bool sistemadetallemaf { get; set; }
        public Nullable<int> isuso { get; set; }
        public string uuid { get; set; }
        public Nullable<int> idencargo { get; set; }
    
        public virtual matrizanalisisfinanciero matrizanalisisfinanciero { get; set; }
        public virtual razone razone { get; set; }
        public virtual encargo encargo { get; set; }
    }
}
