//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalletiempo
    {
        public int iddt { get; set; }
        public int idia { get; set; }
        public Nullable<int> idchh { get; set; }
        public Nullable<int> idencargo { get; set; }
        public Nullable<int> idindice { get; set; }
        public string idnitcliente { get; set; }
        public string actividaddt { get; set; }
        public string fechainicialdt { get; set; }
        public string fechafinaldt { get; set; }
        public decimal tiempohorasdt { get; set; }
        public string comentariosdt { get; set; }
        public string estadodt { get; set; }
        public Nullable<int> isuso { get; set; }
        public string uuid { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual index index { get; set; }
        public virtual informeactividade informeactividade { get; set; }
    }
}
