//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class detallecuestionario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public detallecuestionario()
        {
            this.detallematrizriesgos = new HashSet<detallematrizriesgo>();
            this.usuarioprogramasaccions = new HashSet<usuarioprogramasaccion>();
        }
    
        public int iddc { get; set; }
        public Nullable<int> idtrcdc { get; set; }
        public Nullable<int> idpapelesdc { get; set; }
        public int idprogramadc { get; set; }
        public string descripciondc { get; set; }
        public string fechacreadodc { get; set; }
        public decimal ordendc { get; set; }
        public string estadoprocedimientodc { get; set; }
        public string comentariodc { get; set; }
        public string fechasupervision { get; set; }
        public Nullable<int> idvisitadc { get; set; }
        public Nullable<int> idtprocedimientodc { get; set; }
        public Nullable<int> idpadredc { get; set; }
        public string estadodc { get; set; }
        public Nullable<int> isuso { get; set; }
        public Nullable<int> idrepositorio { get; set; }
        public Nullable<int> idcedulas { get; set; }
        public Nullable<int> idgenerico { get; set; }
        public string tabla { get; set; }
        public Nullable<int> iddcedulas { get; set; }
        public string uuid { get; set; }
    
        public virtual cedula cedula { get; set; }
        public virtual detallecedula detallecedula { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detallematrizriesgo> detallematrizriesgos { get; set; }
        public virtual tiporespuestacuestionario tiporespuestacuestionario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usuarioprogramasaccion> usuarioprogramasaccions { get; set; }
        public virtual programa programa { get; set; }
        public virtual repositorio repositorio { get; set; }
        public virtual repositorio repositorio1 { get; set; }
        public virtual tipoprocedimiento tipoprocedimiento { get; set; }
        public virtual visita visita { get; set; }
    }
}
