//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalleprograma
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public detalleprograma()
        {
            this.detallematrizriesgos = new HashSet<detallematrizriesgo>();
            this.usuarioprogramasaccions = new HashSet<usuarioprogramasaccion>();
        }
    
        public int iddp { get; set; }
        public Nullable<int> idtprocedimientodp { get; set; }
        public int idprogramadp { get; set; }
        public Nullable<int> idpapelesdp { get; set; }
        public string descripciondp { get; set; }
        public string fechacreadodp { get; set; }
        public decimal ordendp { get; set; }
        public string fechainidp { get; set; }
        public string fechafindp { get; set; }
        public Nullable<decimal> horaplandp { get; set; }
        public Nullable<decimal> horaejecdp { get; set; }
        public string estadoprocedimientodp { get; set; }
        public string comentariodp { get; set; }
        public string estadodp { get; set; }
        public string fechasupervision { get; set; }
        public Nullable<int> idvisitadp { get; set; }
        public Nullable<int> idpadredp { get; set; }
        public Nullable<int> isuso { get; set; }
        public Nullable<int> idrepositorio { get; set; }
        public Nullable<int> idcedula { get; set; }
        public Nullable<int> idgenerico { get; set; }
        public string tabla { get; set; }
        public Nullable<int> iddcedulas { get; set; }
        public string uuid { get; set; }
        public Nullable<int> idnotaspt { get; set; }
        public Nullable<int> idagenda { get; set; }
        public Nullable<int> idusuarioejecuto { get; set; }
    
        public virtual agenda agenda { get; set; }
        public virtual cedula cedula { get; set; }
        public virtual detallecedula detallecedula { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detallematrizriesgo> detallematrizriesgos { get; set; }
        public virtual tipoprocedimiento tipoprocedimiento { get; set; }
        public virtual detalleprograma detalleprogramas1 { get; set; }
        public virtual detalleprograma detalleprograma1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usuarioprogramasaccion> usuarioprogramasaccions { get; set; }
        public virtual notaspt notaspt { get; set; }
        public virtual papele papele { get; set; }
        public virtual repositorio repositorio { get; set; }
        public virtual usuario usuario { get; set; }
        public virtual visita visita { get; set; }
    }
}
