//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class detallecedula
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public detallecedula()
        {
            this.hallazgos = new HashSet<hallazgo>();
            this.detalleprogramas = new HashSet<detalleprograma>();
            this.detallecedulas1 = new HashSet<detallecedula>();
            this.detallecuestionarios = new HashSet<detallecuestionario>();
        }
    
        public int iddc { get; set; }
        public Nullable<int> idindice { get; set; }
        public Nullable<int> idcedula { get; set; }
        public Nullable<int> idpartida { get; set; }
        public Nullable<int> padreiddc { get; set; }
        public string codigocontabledc { get; set; }
        public Nullable<decimal> saldoactualdc { get; set; }
        public string m1dc { get; set; }
        public string m2dc { get; set; }
        public Nullable<decimal> saldoanteriordc { get; set; }
        public string m3dc { get; set; }
        public string m4dc { get; set; }
        public Nullable<decimal> aumentodc { get; set; }
        public Nullable<decimal> disminuciondc { get; set; }
        public string m5dc { get; set; }
        public string m6dc { get; set; }
        public string m7dc { get; set; }
        public string m8dc { get; set; }
        public Nullable<decimal> saldofinaldc { get; set; }
        public string m9dc { get; set; }
        public string m10dc { get; set; }
        public string fechacreadodc { get; set; }
        public decimal ordendc { get; set; }
        public Nullable<int> isuso { get; set; }
        public string referenciapapel { get; set; }
        public Nullable<int> idgenerico { get; set; }
        public string tabla { get; set; }
        public string usuariocerro { get; set; }
        public string usuarioaprobo { get; set; }
        public string usuariosuperviso { get; set; }
        public string fechasupervision { get; set; }
        public string fechaaprobacion { get; set; }
        public string fechacierre { get; set; }
        public string etapapapel { get; set; }
        public Nullable<int> idencargo { get; set; }
        public string claseregistro { get; set; }
        public string filasoperadas { get; set; }
        public string signooperacion { get; set; }
        public Nullable<int> idcc { get; set; }
        public Nullable<int> iddb { get; set; }
        public Nullable<int> idrepositorio { get; set; }
        public string estadodc { get; set; }
        public string nombrecuenta { get; set; }
        public string uuid { get; set; }
        public Nullable<decimal> cargoreajuste { get; set; }
        public Nullable<decimal> abonoreajuste { get; set; }
        public string m11dc { get; set; }
        public string m12dc { get; set; }
        public string m13dc { get; set; }
        public string m14dc { get; set; }
        public string m15dc { get; set; }
        public string observaciondc { get; set; }
        public Nullable<decimal> cargoreclasificacion { get; set; }
        public Nullable<decimal> abonoreclasificacion { get; set; }
        public Nullable<int> idpapeles { get; set; }
        public Nullable<int> idnotaspt { get; set; }
        public Nullable<int> idagenda { get; set; }
    
        public virtual agenda agenda { get; set; }
        public virtual catalogocuenta catalogocuenta { get; set; }
        public virtual cedula cedula { get; set; }
        public virtual detallebalance detallebalance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hallazgo> hallazgos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalleprograma> detalleprogramas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detallecedula> detallecedulas1 { get; set; }
        public virtual detallecedula detallecedula1 { get; set; }
        public virtual index index { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detallecuestionario> detallecuestionarios { get; set; }
        public virtual encargo encargo { get; set; }
        public virtual notaspt notaspt { get; set; }
        public virtual papele papele { get; set; }
        public virtual partida partida { get; set; }
        public virtual repositorio repositorio { get; set; }
    }
}
