//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class detallebalance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public detallebalance()
        {
            this.confirmaciones = new HashSet<confirmacione>();
            this.detallecedulas = new HashSet<detallecedula>();
            this.materialidads = new HashSet<materialidad>();
        }
    
        public int iddb { get; set; }
        public Nullable<int> idcc { get; set; }
        public Nullable<int> idbalance { get; set; }
        public decimal saldoanteriordb { get; set; }
        public decimal cargodb { get; set; }
        public decimal abonodb { get; set; }
        public decimal saldofinaldb { get; set; }
        public string estadodb { get; set; }
        public Nullable<decimal> orden { get; set; }
        public string comentariodb { get; set; }
        public Nullable<int> isuso { get; set; }
        public string uuid { get; set; }
    
        public virtual balance balance { get; set; }
        public virtual catalogocuenta catalogocuenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<confirmacione> confirmaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detallecedula> detallecedulas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<materialidad> materialidads { get; set; }
    }
}
