//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class estructurasorganica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public estructurasorganica()
        {
            this.contactos = new HashSet<contacto>();
        }
    
        public int idcargoeo { get; set; }
        public Nullable<int> estidcargoeo { get; set; }
        public string idnitcliente { get; set; }
        public string nombrecargoeo { get; set; }
        public string responsabilidadeo { get; set; }
        public string funcionadicionaleo { get; set; }
        public string estadoeo { get; set; }
        public Nullable<int> isuso { get; set; }
        public string uuid { get; set; }
    
        public virtual cliente cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contacto> contactos { get; set; }
        public virtual estructurasorganica estructurasorganicas1 { get; set; }
        public virtual estructurasorganica estructurasorganica1 { get; set; }
    }
}
