//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class firma
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public firma()
        {
            this.correos = new HashSet<correo>();
            this.telefonos = new HashSet<telefono>();
        }
    
        public int idfirma { get; set; }
        public Nullable<int> iddepartamento { get; set; }
        public int idpais { get; set; }
        public int idmunicipio { get; set; }
        public Nullable<int> idusuario { get; set; }
        public string razonsocialfirma { get; set; }
        public string representantefirma { get; set; }
        public string nitfirma { get; set; }
        public string nrcfirma { get; set; }
        public string direccionfirma { get; set; }
        public Nullable<int> numerocvpafirma { get; set; }
        public string fechainscripcioncvpafirma { get; set; }
        public string fechacreadofirma { get; set; }
        public string urlfirma { get; set; }
        public byte[] logofirma { get; set; }
        public string estadofirma { get; set; }
        public Nullable<int> isuso { get; set; }
        public string uuid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<correo> correos { get; set; }
        public virtual departamento departamento { get; set; }
        public virtual municipio municipio { get; set; }
        public virtual pais pais { get; set; }
        public virtual usuario usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<telefono> telefonos { get; set; }
    }
}
