//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class formulasaplicada
    {
        public int idfa { get; set; }
        public Nullable<int> idcc { get; set; }
        public Nullable<int> idratio { get; set; }
        public string descriptorfa { get; set; }
        public bool sistemafa { get; set; }
        public string estadofa { get; set; }
        public Nullable<int> isuso { get; set; }
        public string uuid { get; set; }
    
        public virtual razone razone { get; set; }
    }
}
