//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class formula
    {
        public int idformula { get; set; }
        public Nullable<int> idratio { get; set; }
        public Nullable<int> idtd { get; set; }
        public string descriptorformula { get; set; }
        public bool sistemaformula { get; set; }
        public string estadoformula { get; set; }
        public Nullable<int> isuso { get; set; }
        public string uuid { get; set; }
    
        public virtual ratio ratio { get; set; }
        public virtual tiposdescriptore tiposdescriptore { get; set; }
    }
}
