//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class herramienta
    {
        public int idherramienta { get; set; }
        public Nullable<int> idtp { get; set; }
        public Nullable<int> idth { get; set; }
        public string nombreherramienta { get; set; }
        public string fechacreadoherramienta { get; set; }
        public string autorizadoporherramienta { get; set; }
        public Nullable<decimal> horasplanherramienta { get; set; }
        public string estadoherramienta { get; set; }
        public bool sistemaherramienta { get; set; }
        public Nullable<int> isuso { get; set; }
        public string uuid { get; set; }
    
        public virtual tiposprograma tiposprograma { get; set; }
        public virtual tiposherramienta tiposherramienta { get; set; }
    }
}
