//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class index
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public index()
        {
            this.cedularequerimientos = new HashSet<cedularequerimiento>();
            this.cedulas = new HashSet<cedula>();
            this.detallecedulas = new HashSet<detallecedula>();
            this.detalletiempoes = new HashSet<detalletiempo>();
            this.notaspts = new HashSet<notaspt>();
            this.indices1 = new HashSet<index>();
            this.matrizriesgos = new HashSet<matrizriesgo>();
            this.repositorios = new HashSet<repositorio>();
            this.programas = new HashSet<programa>();
        }
    
        public int idindice { get; set; }
        public Nullable<int> idmr { get; set; }
        public Nullable<int> idpapeles { get; set; }
        public Nullable<int> idmaf { get; set; }
        public Nullable<int> idencargo { get; set; }
        public Nullable<int> idprograma { get; set; }
        public Nullable<int> indidindice { get; set; }
        public string descripcionindice { get; set; }
        public decimal ordenindice { get; set; }
        public string referenciaindice { get; set; }
        public bool obligatorioindice { get; set; }
        public bool sistemaindice { get; set; }
        public string estadoindice { get; set; }
        public Nullable<int> idtcindice { get; set; }
        public Nullable<int> idteiindice { get; set; }
        public Nullable<int> idgenericoindice { get; set; }
        public string tablaindice { get; set; }
        public Nullable<int> isuso { get; set; }
        public string uuid { get; set; }
        public Nullable<int> idagenda { get; set; }
    
        public virtual agenda agenda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cedularequerimiento> cedularequerimientos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cedula> cedulas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detallecedula> detallecedulas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalletiempo> detalletiempoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notaspt> notaspts { get; set; }
        public virtual tipoelementoindice tipoelementoindice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<index> indices1 { get; set; }
        public virtual index index1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<matrizriesgo> matrizriesgos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<repositorio> repositorios { get; set; }
        public virtual tipocarpeta tipocarpeta { get; set; }
        public virtual matrizriesgo matrizriesgo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<programa> programas { get; set; }
    }
}
