//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class informeactividade
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public informeactividade()
        {
            this.detalletiempoes = new HashSet<detalletiempo>();
        }
    
        public int idia { get; set; }
        public Nullable<int> idusuario { get; set; }
        public Nullable<int> usuidusuario { get; set; }
        public string fechainicialia { get; set; }
        public string fechafinalia { get; set; }
        public Nullable<decimal> totalhorasia { get; set; }
        public string observacionesia { get; set; }
        public string aprobacionia { get; set; }
        public string fechaaprobacionia { get; set; }
        public string estadoia { get; set; }
        public Nullable<int> isuso { get; set; }
        public string uuid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalletiempo> detalletiempoes { get; set; }
        public virtual usuario usuario { get; set; }
        public virtual usuario usuario1 { get; set; }
    }
}
