//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class marcasestandare
    {
        public int idme { get; set; }
        public Nullable<int> idusuario { get; set; }
        public string marcame { get; set; }
        public string significadome { get; set; }
        public string fechahoyme { get; set; }
        public string tipografiame { get; set; }
        public Nullable<decimal> tamaniotipografiame { get; set; }
        public string estadome { get; set; }
        public bool sistemame { get; set; }
        public Nullable<int> isuso { get; set; }
        public string uuid { get; set; }
    
        public virtual usuario usuario { get; set; }
    }
}
