//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class materialidad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public materialidad()
        {
            this.detallematrizriesgos = new HashSet<detallematrizriesgo>();
            this.materialidad1 = new HashSet<materialidad>();
        }
    
        public int idmaterialidad { get; set; }
        public string descripcionmaterialidad { get; set; }
        public bool sistemamaterialidad { get; set; }
        public string estadomaterialidad { get; set; }
        public Nullable<int> idencargo { get; set; }
        public Nullable<int> padreidmaterialidad { get; set; }
        public Nullable<decimal> valormaterialidad { get; set; }
        public Nullable<int> idbalance { get; set; }
        public Nullable<int> iddb { get; set; }
        public Nullable<decimal> porcentajematerialidad { get; set; }
        public string fechacreado { get; set; }
        public string fechasupervision { get; set; }
        public string fechaaprobacion { get; set; }
        public string fechacierre { get; set; }
        public string usuariocreo { get; set; }
        public string usuariocerro { get; set; }
        public string usuariosuperviso { get; set; }
        public string usuarioaprobo { get; set; }
        public string etapapapel { get; set; }
        public string uuid { get; set; }
    
        public virtual balance balance { get; set; }
        public virtual detallebalance detallebalance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detallematrizriesgo> detallematrizriesgos { get; set; }
        public virtual encargo encargo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<materialidad> materialidad1 { get; set; }
        public virtual materialidad materialidad2 { get; set; }
    }
}
