//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class matrizriesgo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public matrizriesgo()
        {
            this.detallematrizriesgos = new HashSet<detallematrizriesgo>();
            this.indices = new HashSet<index>();
        }
    
        public int idmr { get; set; }
        public Nullable<int> idindice { get; set; }
        public Nullable<int> idencargo { get; set; }
        public Nullable<int> idbalance { get; set; }
        public string fechasistemamr { get; set; }
        public string fechaevaluacionmr { get; set; }
        public string estadomr { get; set; }
        public string referenciamr { get; set; }
        public Nullable<int> isuso { get; set; }
        public string usuarioaprobo { get; set; }
        public string fechacierre { get; set; }
        public string fechasupervision { get; set; }
        public string fechaaprobacion { get; set; }
        public string usuariocerro { get; set; }
        public string usuariosuperviso { get; set; }
        public string uuid { get; set; }
        public string etapapapel { get; set; }
    
        public virtual balance balance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detallematrizriesgo> detallematrizriesgos { get; set; }
        public virtual encargo encargo { get; set; }
        public virtual index index { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<index> indices { get; set; }
    }
}
