//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SGPTEntidades : DbContext
    {
        public SGPTEntidades()
            : base("name=SGPTEntidades")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<actividade> actividades { get; set; }
        public virtual DbSet<agenda> agendas { get; set; }
        public virtual DbSet<asignacione> asignaciones { get; set; }
        public virtual DbSet<balance> balances { get; set; }
        public virtual DbSet<bitacora> bitacoras { get; set; }
        public virtual DbSet<catalogocuenta> catalogocuentas { get; set; }
        public virtual DbSet<cedulacontacto> cedulacontactos { get; set; }
        public virtual DbSet<cedulacorrespondencia> cedulacorrespondencias { get; set; }
        public virtual DbSet<cedularequerimiento> cedularequerimientos { get; set; }
        public virtual DbSet<cedulareunione> cedulareuniones { get; set; }
        public virtual DbSet<cedula> cedulas { get; set; }
        public virtual DbSet<cedulaslegale> cedulaslegales { get; set; }
        public virtual DbSet<clasecuenta> clasecuentas { get; set; }
        public virtual DbSet<clasesbalance> clasesbalances { get; set; }
        public virtual DbSet<clasificacione> clasificaciones { get; set; }
        public virtual DbSet<cliente> clientes { get; set; }
        public virtual DbSet<conexione> conexiones { get; set; }
        public virtual DbSet<confirmacione> confirmaciones { get; set; }
        public virtual DbSet<contactocliente> contactoclientes { get; set; }
        public virtual DbSet<contacto> contactos { get; set; }
        public virtual DbSet<correo> correos { get; set; }
        public virtual DbSet<correspondencia> correspondencias { get; set; }
        public virtual DbSet<correspondenciatipos> correspondenciatipos { get; set; }
        public virtual DbSet<costohistoricohora> costohistoricohoras { get; set; }
        public virtual DbSet<cronograma> cronogramas { get; set; }
        public virtual DbSet<departamento> departamentos { get; set; }
        public virtual DbSet<designacione> designaciones { get; set; }
        public virtual DbSet<detallebalance> detallebalances { get; set; }
        public virtual DbSet<detallecedula> detallecedulas { get; set; }
        public virtual DbSet<detallecronograma> detallecronogramas { get; set; }
        public virtual DbSet<detallecuestionario> detallecuestionarios { get; set; }
        public virtual DbSet<detalledocumento> detalledocumentos { get; set; }
        public virtual DbSet<detalleherramienta> detalleherramientas { get; set; }
        public virtual DbSet<detallematrizriesgo> detallematrizriesgos { get; set; }
        public virtual DbSet<detalleplantillaindice> detalleplantillaindices { get; set; }
        public virtual DbSet<detalleprograma> detalleprogramas { get; set; }
        public virtual DbSet<detallesmaf> detallesmafs { get; set; }
        public virtual DbSet<detalletiempo> detalletiempoes { get; set; }
        public virtual DbSet<documento> documentos { get; set; }
        public virtual DbSet<elemento> elementos { get; set; }
        public virtual DbSet<encargo> encargos { get; set; }
        public virtual DbSet<estructuraestadofinanciero> estructuraestadofinancieros { get; set; }
        public virtual DbSet<estructurasorganica> estructurasorganicas { get; set; }
        public virtual DbSet<firma> firmas { get; set; }
        public virtual DbSet<formula> formulas { get; set; }
        public virtual DbSet<formulasaplicada> formulasaplicadas { get; set; }
        public virtual DbSet<hallazgo> hallazgos { get; set; }
        public virtual DbSet<herramienta> herramientas { get; set; }
        public virtual DbSet<historicoscontrasenia> historicoscontrasenias { get; set; }
        public virtual DbSet<index> indices { get; set; }
        public virtual DbSet<informeactividade> informeactividades { get; set; }
        public virtual DbSet<legalnorma> legalnormas { get; set; }
        public virtual DbSet<marcasauditoria> marcasauditorias { get; set; }
        public virtual DbSet<marcasestandare> marcasestandares { get; set; }
        public virtual DbSet<materialidad> materialidads { get; set; }
        public virtual DbSet<matrizanalisisfinanciero> matrizanalisisfinancieroes { get; set; }
        public virtual DbSet<matrizriesgo> matrizriesgos { get; set; }
        public virtual DbSet<moneda> monedas { get; set; }
        public virtual DbSet<movimiento> movimientos { get; set; }
        public virtual DbSet<municipio> municipios { get; set; }
        public virtual DbSet<normativa> normativas { get; set; }
        public virtual DbSet<notaspt> notaspts { get; set; }
        public virtual DbSet<obligacioneslegale> obligacioneslegales { get; set; }
        public virtual DbSet<opcionesrole> opcionesroles { get; set; }
        public virtual DbSet<pais> paises { get; set; }
        public virtual DbSet<papele> papeles { get; set; }
        public virtual DbSet<partida> partidas { get; set; }
        public virtual DbSet<periodo> periodos { get; set; }
        public virtual DbSet<permisosrolesusuario> permisosrolesusuarios { get; set; }
        public virtual DbSet<persona> personas { get; set; }
        public virtual DbSet<pista> pistas { get; set; }
        public virtual DbSet<plantillaindice> plantillaindices { get; set; }
        public virtual DbSet<plantilla> plantillas { get; set; }
        public virtual DbSet<procesosauditoria> procesosauditorias { get; set; }
        public virtual DbSet<programa> programas { get; set; }
        public virtual DbSet<ratio> ratios { get; set; }
        public virtual DbSet<razone> razones { get; set; }
        public virtual DbSet<repositorio> repositorios { get; set; }
        public virtual DbSet<requerimiento> requerimientos { get; set; }
        public virtual DbSet<reunione> reuniones { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<simbolo> simbolos { get; set; }
        public virtual DbSet<sistemascontable> sistemascontables { get; set; }
        public virtual DbSet<telefono> telefonos { get; set; }
        public virtual DbSet<tipocarpeta> tipocarpetas { get; set; }
        public virtual DbSet<tipoconfirmacione> tipoconfirmaciones { get; set; }
        public virtual DbSet<tipoelementoindice> tipoelementoindices { get; set; }
        public virtual DbSet<tipopartida> tipopartidas { get; set; }
        public virtual DbSet<tipoprocedimiento> tipoprocedimientoes { get; set; }
        public virtual DbSet<tiporespuestacuestionario> tiporespuestacuestionarios { get; set; }
        public virtual DbSet<tiposauditoria> tiposauditorias { get; set; }
        public virtual DbSet<tiposcedula> tiposcedulas { get; set; }
        public virtual DbSet<tiposdescriptore> tiposdescriptores { get; set; }
        public virtual DbSet<tiposherramienta> tiposherramientas { get; set; }
        public virtual DbSet<tiposprograma> tiposprogramas { get; set; }
        public virtual DbSet<tipostelefono> tipostelefonos { get; set; }
        public virtual DbSet<usuarioherramientasaccion> usuarioherramientasaccions { get; set; }
        public virtual DbSet<usuariomatanalisfinancaccion> usuariomatanalisfinancaccions { get; set; }
        public virtual DbSet<usuarioprogramasaccion> usuarioprogramasaccions { get; set; }
        public virtual DbSet<usuariorequerimientosaccion> usuariorequerimientosaccions { get; set; }
        public virtual DbSet<usuario> usuarios { get; set; }
        public virtual DbSet<visita> visitas { get; set; }
    }
}
