//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class movimiento
    {
        public int idmovimiento { get; set; }
        public Nullable<int> idcc { get; set; }
        public int idpartida { get; set; }
        public Nullable<decimal> cargomovimiento { get; set; }
        public Nullable<decimal> abonomovimiento { get; set; }
        public string estadomovimiento { get; set; }
        public string uuid { get; set; }
        public Nullable<int> idencargo { get; set; }
    
        public virtual catalogocuenta catalogocuenta { get; set; }
        public virtual encargo encargo { get; set; }
        public virtual partida partida { get; set; }
    }
}
