//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class normativa
    {
        public int idnormativa { get; set; }
        public Nullable<int> idln { get; set; }
        public Nullable<int> idusuario { get; set; }
        public string nombrenormativa { get; set; }
        public string nombreabreviadonormativa { get; set; }
        public string fechaemisionnormativa { get; set; }
        public string fechavigencianormativa { get; set; }
        public string fechacreadonormativa { get; set; }
        public byte[] binarionormativa { get; set; }
        public decimal ordennormativa { get; set; }
        public bool sistemanormativa { get; set; }
        public string estadonormativa { get; set; }
        public string nombrearchivonormativa { get; set; }
        public Nullable<int> isuso { get; set; }
        public string uuid { get; set; }
    
        public virtual legalnorma legalnorma { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
