//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class notaspt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public notaspt()
        {
            this.cedulas = new HashSet<cedula>();
            this.detallecedulas = new HashSet<detallecedula>();
            this.detalleprogramas = new HashSet<detalleprograma>();
        }
    
        public int idnotaspt { get; set; }
        public string descripcionnotaspt { get; set; }
        public string fechacreadonotaspt { get; set; }
        public Nullable<int> idusuariocreador { get; set; }
        public Nullable<int> idgenerico { get; set; }
        public string tabla { get; set; }
        public string estadonota { get; set; }
        public Nullable<int> idencargo { get; set; }
        public Nullable<int> idindice { get; set; }
        public Nullable<int> idcedula { get; set; }
        public string referenciapapel { get; set; }
        public string usuariocerro { get; set; }
        public string usuarioaprobo { get; set; }
        public string usuariosuperviso { get; set; }
        public string fechasupervision { get; set; }
        public string fechaaprobacion { get; set; }
        public string fechacierre { get; set; }
        public string etapapapel { get; set; }
        public string uuid { get; set; }
        public string numnotapt { get; set; }
        public Nullable<int> isuso { get; set; }
    
        public virtual cedula cedula { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cedula> cedulas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detallecedula> detallecedulas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalleprograma> detalleprogramas { get; set; }
        public virtual encargo encargo { get; set; }
        public virtual index index { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
