//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class obligacioneslegale
    {
        public int idol { get; set; }
        public Nullable<int> idusuario { get; set; }
        public Nullable<int> oblidol { get; set; }
        public Nullable<int> idnormativa { get; set; }
        public string descripcionol { get; set; }
        public string tipoobligacionol { get; set; }
        public string frecuenciaol { get; set; }
        public string articulool { get; set; }
        public Nullable<decimal> ordenol { get; set; }
        public string estadool { get; set; }
        public bool sistemaol { get; set; }
        public Nullable<int> isuso { get; set; }
        public string uuid { get; set; }
    
        public virtual obligacioneslegale obligacioneslegales1 { get; set; }
        public virtual obligacioneslegale obligacioneslegale1 { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
