//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class opcionesrole
    {
        public int idor { get; set; }
        public Nullable<int> idrol { get; set; }
        public string nombreopcionor { get; set; }
        public bool crearor { get; set; }
        public bool eliminaror { get; set; }
        public bool consultaror { get; set; }
        public bool editaror { get; set; }
        public bool impresionor { get; set; }
        public bool exportacionor { get; set; }
        public bool revisaror { get; set; }
        public bool aprobaror { get; set; }
        public string estadoor { get; set; }
        public bool sistemaor { get; set; }
        public string menuor { get; set; }
        public string submenuor { get; set; }
        public string subsubmenuor { get; set; }
        public Nullable<bool> mostrarenmenuor { get; set; }
        public Nullable<int> isuso { get; set; }
        public string uuid { get; set; }
    
        public virtual role role { get; set; }
    }
}
