//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class papele
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public papele()
        {
            this.cedulacorrespondencias = new HashSet<cedulacorrespondencia>();
            this.cedularequerimientos = new HashSet<cedularequerimiento>();
            this.cedulas = new HashSet<cedula>();
            this.detallecedulas = new HashSet<detallecedula>();
            this.detalleprogramas = new HashSet<detalleprograma>();
            this.repositorios = new HashSet<repositorio>();
        }
    
        public int idpapeles { get; set; }
        public int idcronograma { get; set; }
        public Nullable<int> idusuario { get; set; }
        public string nombrepapeles { get; set; }
        public string fechaeditadopapeles { get; set; }
        public byte[] pdfpapeles { get; set; }
        public string estadopapeles { get; set; }
        public Nullable<int> idencargopapeles { get; set; }
        public string referenciapapeles { get; set; }
        public string idnitclientepapeles { get; set; }
        public Nullable<int> isuso { get; set; }
        public string tipoarchivopapeles { get; set; }
        public byte[] binariopapeles { get; set; }
        public string nombrepdf { get; set; }
        public string nombrebinario { get; set; }
        public string referencia { get; set; }
        public string usuariocerro { get; set; }
        public string usuarioaprobo { get; set; }
        public string usuariosuperviso { get; set; }
        public string fechasupervision { get; set; }
        public string fechaaprobacion { get; set; }
        public string fechacierre { get; set; }
        public string etapapapel { get; set; }
        public Nullable<int> iddocumento { get; set; }
        public string uuid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cedulacorrespondencia> cedulacorrespondencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cedularequerimiento> cedularequerimientos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cedula> cedulas { get; set; }
        public virtual cliente cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detallecedula> detallecedulas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalleprograma> detalleprogramas { get; set; }
        public virtual documento documento { get; set; }
        public virtual encargo encargo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<repositorio> repositorios { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
