//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class partida
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public partida()
        {
            this.detallecedulas = new HashSet<detallecedula>();
            this.movimientos = new HashSet<movimiento>();
        }
    
        public int idpartida { get; set; }
        public Nullable<int> idcedula { get; set; }
        public Nullable<int> idbalance { get; set; }
        public Nullable<int> idtp { get; set; }
        public decimal numeropartida { get; set; }
        public string conceptopartida { get; set; }
        public string fechapartida { get; set; }
        public string fechasistemapartida { get; set; }
        public string aprobadapartida { get; set; }
        public string elaboradapartida { get; set; }
        public string comentariopartida { get; set; }
        public string clienteaplicopartida { get; set; }
        public decimal sumacargopartida { get; set; }
        public decimal sumaabonopartida { get; set; }
        public string estadopartida { get; set; }
        public Nullable<int> isuso { get; set; }
        public string referenciapapel { get; set; }
        public Nullable<int> idgenerico { get; set; }
        public string tabla { get; set; }
        public string usuariocerro { get; set; }
        public string usuarioaprobo { get; set; }
        public string usuariosuperviso { get; set; }
        public string fechasupervision { get; set; }
        public string fechaaprobacion { get; set; }
        public string fechacierre { get; set; }
        public string etapapapel { get; set; }
        public Nullable<int> idencargo { get; set; }
        public string uuid { get; set; }
    
        public virtual balance balance { get; set; }
        public virtual cedula cedula { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detallecedula> detallecedulas { get; set; }
        public virtual encargo encargo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<movimiento> movimientos { get; set; }
        public virtual tipopartida tipopartida { get; set; }
    }
}
