//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class plantilla
    {
        public int idplantilla { get; set; }
        public int idusuario { get; set; }
        public Nullable<int> iddd { get; set; }
        public string nombreplantilla { get; set; }
        public string comentarioplantilla { get; set; }
        public decimal versionplantilla { get; set; }
        public string fechacreadoplantilla { get; set; }
        public string tipoarchivoplantilla { get; set; }
        public byte[] ficherobinarioplantilla { get; set; }
        public bool sistemaplantilla { get; set; }
        public string estadoplantilla { get; set; }
        public string nombrearchivoplantilla { get; set; }
        public Nullable<int> isuso { get; set; }
        public string uuid { get; set; }
    
        public virtual detalledocumento detalledocumento { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
