//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class plantillaindice
    {
        public int idpi { get; set; }
        public Nullable<int> idusuario { get; set; }
        public Nullable<int> idta { get; set; }
        public string descripcionpi { get; set; }
        public bool sistemapi { get; set; }
        public string estadopi { get; set; }
        public string fechacreadopi { get; set; }
        public Nullable<int> idtcpi { get; set; }
        public Nullable<int> isuso { get; set; }
        public string uuid { get; set; }
    
        public virtual tiposauditoria tiposauditoria { get; set; }
        public virtual usuario usuario { get; set; }
        public virtual tipocarpeta tipocarpeta { get; set; }
    }
}
