//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class programa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public programa()
        {
            this.detallecuestionarios = new HashSet<detallecuestionario>();
            this.detallematrizriesgos = new HashSet<detallematrizriesgo>();
            this.usuarioprogramasaccions = new HashSet<usuarioprogramasaccion>();
        }
    
        public int idprograma { get; set; }
        public Nullable<int> idthprograma { get; set; }
        public Nullable<int> idtpprograma { get; set; }
        public Nullable<int> idindiceprograma { get; set; }
        public Nullable<int> idcedulaprograma { get; set; }
        public Nullable<int> idpapelesprograma { get; set; }
        public string nombreprograma { get; set; }
        public string fechahoyprograma { get; set; }
        public Nullable<decimal> horasplanprograma { get; set; }
        public string estadoprograma { get; set; }
        public string etapaprograma { get; set; }
        public Nullable<decimal> horasejecucionprograma { get; set; }
        public int idencargoprograma { get; set; }
        public string referenciaprograma { get; set; }
        public string fechacierre { get; set; }
        public string fechasupervision { get; set; }
        public string fechaaprobacion { get; set; }
        public Nullable<int> isuso { get; set; }
        public string uuid { get; set; }
        public Nullable<int> idagenda { get; set; }
        public string usuarioaprobo { get; set; }
        public string usuariocerro { get; set; }
        public string usuariosuperviso { get; set; }
    
        public virtual agenda agenda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detallecuestionario> detallecuestionarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detallematrizriesgo> detallematrizriesgos { get; set; }
        public virtual encargo encargo { get; set; }
        public virtual index index { get; set; }
        public virtual tiposherramienta tiposherramienta { get; set; }
        public virtual tiposprograma tiposprograma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usuarioprogramasaccion> usuarioprogramasaccions { get; set; }
    }
}
