//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class repositorio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public repositorio()
        {
            this.cedulas = new HashSet<cedula>();
            this.cedulaslegales = new HashSet<cedulaslegale>();
            this.confirmaciones = new HashSet<confirmacione>();
            this.detallecedulas = new HashSet<detallecedula>();
            this.detallecuestionarios = new HashSet<detallecuestionario>();
            this.detallecuestionarios1 = new HashSet<detallecuestionario>();
            this.detalleprogramas = new HashSet<detalleprograma>();
        }
    
        public int idrepositorio { get; set; }
        public Nullable<int> idpapeles { get; set; }
        public Nullable<int> idencargo { get; set; }
        public Nullable<int> iddocumento { get; set; }
        public Nullable<int> idindice { get; set; }
        public string nombrerepositorio { get; set; }
        public string comentariorepositorio { get; set; }
        public Nullable<decimal> versionrepositorio { get; set; }
        public string fechacreadorepositorio { get; set; }
        public string tipoarchivorepositorio { get; set; }
        public byte[] pdfrepositorio { get; set; }
        public string estadorepositorio { get; set; }
        public Nullable<int> isuso { get; set; }
        public byte[] binariorepositorio { get; set; }
        public string nombrepdf { get; set; }
        public string nombrebinariorepositorio { get; set; }
        public string referenciarepositorio { get; set; }
        public Nullable<int> idgenerico { get; set; }
        public string tabla { get; set; }
        public string usuariocerro { get; set; }
        public string usuarioaprobo { get; set; }
        public string usuariosuperviso { get; set; }
        public string fechasupervision { get; set; }
        public string fechaaprobacion { get; set; }
        public string fechacierre { get; set; }
        public string etapapapel { get; set; }
        public string uuid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cedula> cedulas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cedulaslegale> cedulaslegales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<confirmacione> confirmaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detallecedula> detallecedulas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detallecuestionario> detallecuestionarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detallecuestionario> detallecuestionarios1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalleprograma> detalleprogramas { get; set; }
        public virtual documento documento { get; set; }
        public virtual encargo encargo { get; set; }
        public virtual index index { get; set; }
        public virtual papele papele { get; set; }
    }
}
