//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class requerimiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public requerimiento()
        {
            this.usuariorequerimientosaccions = new HashSet<usuariorequerimientosaccion>();
        }
    
        public int idrequerimiento { get; set; }
        public Nullable<decimal> ordenrequerimiento { get; set; }
        public string descripcionrequerimiento { get; set; }
        public string estadorequerimiento { get; set; }
        public bool sistemarequerimiento { get; set; }
        public string uuid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usuariorequerimientosaccion> usuariorequerimientosaccions { get; set; }
    }
}
