//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class reunione
    {
        public int idreunion { get; set; }
        public Nullable<int> idusuario { get; set; }
        public Nullable<int> usuidusuario { get; set; }
        public string idnitcliente { get; set; }
        public string fechareunion { get; set; }
        public Nullable<decimal> tiempoduracionreunion { get; set; }
        public string participanteexternoreunion { get; set; }
        public string participantesinternoreunion { get; set; }
        public string asuntoreunion { get; set; }
        public string conclusionesreunion { get; set; }
        public string aprobacionreunion { get; set; }
        public string estadoreunion { get; set; }
        public string fechaaprobacionreunion { get; set; }
        public Nullable<int> isuso { get; set; }
        public string uuid { get; set; }
    
        public virtual usuario usuario { get; set; }
        public virtual usuario usuario1 { get; set; }
    }
}
