//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class simbolo
    {
        public int idsimbolo { get; set; }
        public Nullable<int> idtd { get; set; }
        public string caractersimbolo { get; set; }
        public string estadosimbolo { get; set; }
        public bool sistemasimbolo { get; set; }
        public Nullable<int> isuso { get; set; }
        public string uuid { get; set; }
    
        public virtual tiposdescriptore tiposdescriptore { get; set; }
    }
}
