//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class sistemascontable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sistemascontable()
        {
            this.balances = new HashSet<balance>();
            this.catalogocuentas = new HashSet<catalogocuenta>();
            this.elementos = new HashSet<elemento>();
        }
    
        public int idsc { get; set; }
        public Nullable<int> idmoneda { get; set; }
        public string idnitcliente { get; set; }
        public int ideef { get; set; }
        public string fechasc { get; set; }
        public int digitoscuentamayorsc { get; set; }
        public int digitosrubroscontablessc { get; set; }
        public string periodoiniciosc { get; set; }
        public string periodofinsc { get; set; }
        public string estadosc { get; set; }
        public Nullable<int> idencargodsc { get; set; }
        public Nullable<int> isuso { get; set; }
        public string uuid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<balance> balances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalogocuenta> catalogocuentas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<elemento> elementos { get; set; }
        public virtual encargo encargo { get; set; }
        public virtual estructuraestadofinanciero estructuraestadofinanciero { get; set; }
        public virtual moneda moneda { get; set; }
    }
}
