//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipocarpeta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tipocarpeta()
        {
            this.indices = new HashSet<index>();
            this.plantillaindices = new HashSet<plantillaindice>();
            this.tipocarpeta1 = new HashSet<tipocarpeta>();
        }
    
        public int idtc { get; set; }
        public string descripciontc { get; set; }
        public bool sistematc { get; set; }
        public string estadotc { get; set; }
        public Nullable<int> idencargotc { get; set; }
        public Nullable<int> padreidtc { get; set; }
        public Nullable<int> isuso { get; set; }
        public string usuariocerro { get; set; }
        public string usuarioaprobo { get; set; }
        public string usuariosuperviso { get; set; }
        public string fechasupervision { get; set; }
        public string fechaaprobacion { get; set; }
        public string fechacierre { get; set; }
        public string etapapapel { get; set; }
        public string uuid { get; set; }
    
        public virtual encargo encargo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<index> indices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<plantillaindice> plantillaindices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tipocarpeta> tipocarpeta1 { get; set; }
        public virtual tipocarpeta tipocarpeta2 { get; set; }
    }
}
