//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipoconfirmacione
    {
        public int idtconfirmacion { get; set; }
        public string descripciontconfirmacion { get; set; }
        public bool sistematconfirmacion { get; set; }
        public string estadotconfirmacion { get; set; }
        public string uuid { get; set; }
    }
}
