//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuariomatanalisfinancaccion
    {
        public int idumafa { get; set; }
        public Nullable<int> idmaf { get; set; }
        public Nullable<int> idusuario { get; set; }
        public string rolumafa { get; set; }
        public string fechacreadoumafa { get; set; }
        public string estadoumafa { get; set; }
        public Nullable<int> isuso { get; set; }
        public string uuid { get; set; }
    
        public virtual matrizanalisisfinanciero matrizanalisisfinanciero { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
