//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarioherramientasaccion
    {
        public int iduha { get; set; }
        public int idherramienta { get; set; }
        public Nullable<int> idusuario { get; set; }
        public string roluha { get; set; }
        public string fechacreadouha { get; set; }
        public string estadouha { get; set; }
        public Nullable<int> isuso { get; set; }
        public string uuid { get; set; }
    
        public virtual usuario usuario { get; set; }
    }
}
